version: '2'

networks:
    lunch_api-net:
        driver: bridge

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ./src/:/usr/src/app
        container_name: lunchladies-app
        networks:
            - lunch_api-net
            - default

### adonisjs Container ###########################

    adonisjs:
        build:
            context: ./dockers/adonisjs
        volumes_from:
            - applications
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
            - 8888:8888
        expose:
            - 8888
        #tty: true
        container_name: lunchladies-adonisjs
        networks:
            - lunch_api-net
            - default

### MYSQL CONTAINER #########################################

    mysql:
        image: mysql:latest
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        volumes_from:
            - mysql-data
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        ports:
            - 3333:3306
        command: mysqld --sql_mode=""
        container_name: lunchladies-mysql
        networks:
            - lunch_api-net
            - default

    mysql-data:
        image: tianon/true
        volumes:
            - ./tmp/mysql-data:/var/lib/mysql
        container_name: lunchladies-mysql-data
### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    redis:
        driver: "local"
